### ISSUE TITLE
Swagger specification for Carbon Black API

### ISSUE THREAD

**Issue by Gabriella439** [carbonblack/cbapi#83]
Would it be possible to publish a [Swagger specification](https://swagger.io/) for Carbon Black's JSON API?  The reason we ask is that this would allow multiple languages to code-generate API bindings using [`swagger-codegen`](https://github.com/swagger-api/swagger-codegen) or something similar

**Comment by jgarman** [comment]
Yes there is already some work underway for this. If you're a Cb Response customer on premise, you already have that swagger definition available.

We took an opposite approach with our Python bindings (https://cbapi.readthedocs.io) where we wrote our own bindings rather than relying on autogenerated bindings. While the codegen'ed bindings were nice, they didn't handle exceptional cases well (for example, re-establishing a live response session if a 404 was received when a command was sent), and there are many places where data formats aren't consistent across different calls.

We will be opening up more swagger docs over time - stay tuned.

**Comment by Gabriella439** [comment]
@jgarman: In our case we do have an evaluation installation of Cb response so if we could obtain the Swagger definitions from that installation then it would solve our use case.  How do we retrieve them?

**Comment by jgarman** [comment]
Take a look at `/var/www/cb-swagger/spec` on your Cb Response server, that should include the JSON swagger spec file.

**Comment by Gabriella439** [comment]
@jgarman: Thank you!  We found the file and that solved the issue for us.  You can close this if you want or leave it open if you plan to use this to track work on the public Swagger specification

**Comment by jgarman** [comment]
We have this planned internally so I will close this issue - glad we could help! Enjoy
